#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#------------------------------------------------------------------------------


# Get application name
application=$(getApplication)

runApplication blockMesh
runApplication $application
#runApplication foamToVTK

if [ ! -d logs ] 
then
  mkdir logs
fi

runApplication foamLog log.$application
